# Generated by Django 5.2.9 on 2025-12-03 22:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор сбора')),
                ('title', models.CharField(max_length=200, verbose_name='Название сбора')),
                ('occasion', models.CharField(choices=[('birthday', 'День рождения'), ('wedding', 'Свадьба'), ('medical', 'Медицинское лечение'), ('charity', 'Благотворительность'), ('education', 'Образование'), ('business', 'Бизнес'), ('other', 'Другое')], max_length=50, verbose_name='Повод сбора')),
                ('description', models.TextField(verbose_name='Описание сбора')),
                ('target_amount_cents', models.BigIntegerField(blank=True, help_text='Укажите только если это НЕ бесконечный сбор', null=True, verbose_name='Целевая сумма (в копейках)')),
                ('collected_amount_cents', models.BigIntegerField(default=0, verbose_name='Собранная сумма (в копейках)')),
                ('contributors_count', models.PositiveIntegerField(default=0, verbose_name='Количество донатеров')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='collects/covers/%Y/%m/%d/', verbose_name='Обложка сбора')),
                ('end_datetime', models.DateTimeField(verbose_name='Дата и время завершения сбора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный сбор')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collects', to=settings.AUTH_USER_MODEL, verbose_name='Автор сбора')),
            ],
            options={
                'verbose_name': 'Групповой сбор',
                'verbose_name_plural': 'Групповые сборы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор платежа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Сумма платежа')),
                ('payment_method', models.CharField(choices=[('card', 'Банковская карта'), ('sbp', 'СБП'), ('qiwi', 'QIWI'), ('yoomoney', 'ЮMoney'), ('other', 'Другое')], max_length=50, verbose_name='Способ оплаты')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к платежу')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Анонимный платеж')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.collect', verbose_name='Сбор')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='collect',
            index=models.Index(fields=['author', 'created_at'], name='api_collect_author__cf1379_idx'),
        ),
        migrations.AddIndex(
            model_name='collect',
            index=models.Index(fields=['is_active', 'end_datetime'], name='api_collect_is_acti_6364d6_idx'),
        ),
        migrations.AddIndex(
            model_name='collect',
            index=models.Index(fields=['occasion'], name='api_collect_occasio_c848c7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['collect', 'created_at'], name='api_payment_collect_8b6b58_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'created_at'], name='api_payment_user_id_a1e894_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='api_payment_payment_38c2ae_idx'),
        ),
    ]
